version: '3.5'

services:
  app:
    build: .
    image: api
    ports:
      - 3000:3000
    working_dir: /usr/src/app
    volumes:
      - '.:/usr/src/app'
      - api-usrlocal:/usr/local/

volumes:
  api-usrlocal:

networks:
  local:
